DROP TABLE IF EXISTS stats CASCADE;

CREATE TABLE IF NOT EXISTS stats (
     id bigint generated by default as identity primary key,
     uri varchar(100),
     app varchar(50),
     ip varchar(100),
     updated timestamp
);